[build-system]
requires = [ "setuptools" ]
build-backend = "setuptools.build_meta"


[project]
name = "template-project-cpp"
version = "0.1.0"

requires-python = ">=3.10"

dependencies = [
    "compdb ~= 0.2.0",
]
