name: "CI"

on:
    pull_request:
    push:
        branches:
            - master

jobs:
    build-linux:
        if: "!contains(github.event.head_commit.message, 'skip ci')"
        runs-on: ubuntu-latest
        permissions:
            id-token: "write"
            contents: "write"
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: recursive
            - uses: DeterminateSystems/nix-installer-action@v14
            - uses: DeterminateSystems/magic-nix-cache-action@v8
            - run: nix develop -c B
            - run: nix develop -c T
            - run: nix develop -c D
            - run: nix build ".#tpcpp"
            - run: nix develop -c pre-commit run --all-files
            - run: nix develop -c cmake --build build/Debug --target doc
            - uses: JamesIves/github-pages-deploy-action@v4
              with:
                  folder: build/Debug/html

    # build-macos:
    #     if: "!contains(github.event.head_commit.message, 'skip ci')"
    #     runs-on: macos-latest
    #     permissions:
    #         id-token: "write"
    #         contents: "read"
    #     steps:
    #         - uses: actions/checkout@v4
    #           with:
    #               submodules: recursive
    #         - uses: DeterminateSystems/nix-installer-action@v14
    #         - uses: DeterminateSystems/magic-nix-cache-action@v8
    #         - run: nix develop -c B
    #         - run: nix develop -c T
    #         - run: nix develop -c D
    #         - run: nix build ".#tpcpp"
    #         - run: nix develop -c pre-commit run --all-files
    #         - run: nix develop -c cmake --build build/Debug --target doc

    build-win-preset-dev:
        if: "!contains(github.event.head_commit.message, 'skip ci')"
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: recursive
            - uses: ilammy/msvc-dev-cmd@v1
            - run: cmake --preset msvc
            - run: cmake --build --preset debug
            - run: ctest --test-dir build -C Debug --output-on-failure

    build-win-no-preset-dev:
        if: "!contains(github.event.head_commit.message, 'skip ci')"
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: recursive
            - uses: Cyberboss/install-winget@v1
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - run: ./tools/install-deps.ps1
              shell: pwsh
            - run: cmake --preset msvc
            - run: cmake --build --preset debug
            - run: ctest --test-dir build -C Debug --output-on-failure
            - run: cmake --build --preset debug --target doc
            - run: ./tools/configure-pre-commit.ps1
              shell: pwsh
            - run: pre-commit run --all
